// SPDX-License-Identifier: MIT
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include "CNA/C/cna.h"

#define CHECK_FN(name, result, parameters) \
    typedef result (*expected_##name) parameters; \
    _Static_assert(__builtin_types_compatible_p(__typeof__(&name), expected_##name), "prototype mismatch: " #name)

CHECK_FN(cna_get_abi_version, uint32_t, (void));
CHECK_FN(cna_error_get_last_info, CNA_Result, (CNA_ErrorInfo*));
CHECK_FN(cna_error_get_last_message_size, CNA_Result, (uint64_t*));
CHECK_FN(cna_error_copy_last_message, CNA_Result, (char*, uint64_t, uint64_t*));
CHECK_FN(cna_game_create, CNA_Result, (const CNA_GameCreateInfo*, CNA_Handle*));
CHECK_FN(cna_game_set_frame_hooks_ext, CNA_Result, (CNA_Handle, const CNA_GameFrameHooks*));
CHECK_FN(cna_game_run, CNA_Result, (CNA_Handle));
CHECK_FN(cna_game_run_one_frame, CNA_Result, (CNA_Handle));
CHECK_FN(cna_game_tick, CNA_Result, (CNA_Handle));
CHECK_FN(cna_game_request_exit, CNA_Result, (CNA_Handle));
CHECK_FN(cna_game_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_game_subscribe, CNA_Result, (CNA_Handle, CNA_GameEvent, CNA_GameEventCallback, void*, CNA_GameEventRegistrationHandle*));
CHECK_FN(cna_game_unsubscribe, CNA_Result, (CNA_GameEventRegistrationHandle));
CHECK_FN(cna_game_get_is_active, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_guide_get_is_visible, CNA_Result, (CNA_Bool*));
CHECK_FN(cna_gamer_services_dispatcher_get_is_initialized, CNA_Result, (CNA_Bool*));
CHECK_FN(cna_gamer_services_dispatcher_set_window_handle, CNA_Result, (uint64_t));
CHECK_FN(cna_gamer_services_dispatcher_initialize, CNA_Result, (CNA_Handle));
CHECK_FN(cna_gamer_services_dispatcher_update, CNA_Result, (void));
CHECK_FN(cna_gamer_services_dispatcher_subscribe_installing_title_update_ext, CNA_Result, (CNA_GamerAsyncCallback, void*, CNA_Handle*));
CHECK_FN(cna_gamer_unsubscribe_ext, CNA_Result, (CNA_Handle));
CHECK_FN(cna_game_get_is_mouse_visible, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_game_set_is_mouse_visible, CNA_Result, (CNA_Handle, CNA_Bool));
CHECK_FN(cna_game_get_is_fixed_time_step, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_game_set_is_fixed_time_step, CNA_Result, (CNA_Handle, CNA_Bool));
CHECK_FN(cna_game_get_target_elapsed_time_ticks, CNA_Result, (CNA_Handle, int64_t*));
CHECK_FN(cna_game_set_target_elapsed_time_ticks, CNA_Result, (CNA_Handle, int64_t));
CHECK_FN(cna_game_get_inactive_sleep_time_ticks, CNA_Result, (CNA_Handle, int64_t*));
CHECK_FN(cna_game_set_inactive_sleep_time_ticks, CNA_Result, (CNA_Handle, int64_t));
CHECK_FN(cna_game_suppress_draw, CNA_Result, (CNA_Handle));
CHECK_FN(cna_game_reset_elapsed_time, CNA_Result, (CNA_Handle));
CHECK_FN(cna_game_set_window_title, CNA_Result, (CNA_Handle, CNA_StringView));
CHECK_FN(cna_game_window_get_title_size, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_game_window_copy_title, CNA_Result, (CNA_Handle, char*, uint64_t, uint64_t*));
CHECK_FN(cna_game_window_get_allow_user_resizing, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_game_window_set_allow_user_resizing, CNA_Result, (CNA_Handle, CNA_Bool));
CHECK_FN(cna_game_window_get_client_bounds, CNA_Result, (CNA_Handle, CNA_Rectangle*));
CHECK_FN(cna_game_window_get_current_orientation, CNA_Result, (CNA_Handle, CNA_DisplayOrientation*));
CHECK_FN(cna_game_window_get_native_handle_ext, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_game_window_get_screen_device_name_size, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_game_window_copy_screen_device_name, CNA_Result, (CNA_Handle, char*, uint64_t, uint64_t*));
CHECK_FN(cna_game_window_begin_screen_device_change, CNA_Result, (CNA_Handle, CNA_Bool));
CHECK_FN(cna_game_window_end_screen_device_change, CNA_Result, (CNA_Handle, CNA_StringView, int32_t, int32_t));
CHECK_FN(cna_game_window_subscribe, CNA_Result, (CNA_Handle, CNA_GameWindowEvent, CNA_GameEventCallback, void*, CNA_GameEventRegistrationHandle*));
CHECK_FN(cna_framework_dispatcher_update, CNA_Result, (CNA_Handle));
CHECK_FN(cna_title_location_get_path_size, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_title_location_copy_path, CNA_Result, (CNA_Handle, char*, uint64_t, uint64_t*));
CHECK_FN(cna_title_location_set_path_ext, CNA_Result, (CNA_Handle, CNA_StringView));
CHECK_FN(cna_title_container_read_ext, CNA_Result, (CNA_Handle, CNA_StringView, uint8_t*, uint64_t, uint64_t*));
CHECK_FN(cna_game_get_content_manager_ext, CNA_Result, (CNA_Handle, CNA_Handle*));
CHECK_FN(cna_content_manager_create, CNA_Result, (CNA_Handle, const CNA_ContentManagerCreateInfo*, CNA_Handle*));
CHECK_FN(cna_content_manager_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_content_manager_get_root_directory_size, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_content_manager_copy_root_directory, CNA_Result, (CNA_Handle, char*, uint64_t, uint64_t*));
CHECK_FN(cna_content_manager_set_root_directory, CNA_Result, (CNA_Handle, CNA_StringView));
CHECK_FN(cna_content_manager_unload, CNA_Result, (CNA_Handle));
CHECK_FN(cna_content_manager_load_texture2d, CNA_Result, (CNA_Handle, CNA_StringView, CNA_Handle*));
CHECK_FN(cna_graphics_device_manager_create, CNA_Result, (CNA_Handle, CNA_GraphicsDeviceManagerHandle*));
CHECK_FN(cna_graphics_device_manager_get_graphics_device, CNA_Result, (CNA_GraphicsDeviceManagerHandle, CNA_Handle*));
CHECK_FN(cna_graphics_device_manager_dispose, CNA_Result, (CNA_GraphicsDeviceManagerHandle));
CHECK_FN(cna_graphics_device_manager_destroy, CNA_Result, (CNA_GraphicsDeviceManagerHandle));
CHECK_FN(cna_graphics_device_get_viewport, CNA_Result, (CNA_Handle, CNA_Viewport*));
CHECK_FN(cna_graphics_device_clear_rgba, CNA_Result, (CNA_Handle, float, float, float, float));
CHECK_FN(cna_graphics_device_get_texture, CNA_Result, (CNA_Handle, CNA_ShaderStage, uint32_t, CNA_TextureSlotInfo*));
CHECK_FN(cna_graphics_device_set_texture, CNA_Result, (CNA_Handle, CNA_ShaderStage, uint32_t, CNA_Handle));
CHECK_FN(cna_texture2d_create_from_encoded_memory, CNA_Result, (CNA_Handle, const uint8_t*, uint64_t, const CNA_Texture2DDecodeInfo*, CNA_Handle*));
CHECK_FN(cna_texture2d_get_info, CNA_Result, (CNA_Handle, CNA_Texture2DInfo*));
CHECK_FN(cna_texture2d_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_sprite_batch_create, CNA_Result, (CNA_Handle, CNA_Handle*));
CHECK_FN(cna_sprite_batch_begin, CNA_Result, (CNA_Handle, const CNA_SpriteBatchBeginInfo*));
CHECK_FN(cna_sprite_batch_submit_scaled_many, CNA_Result, (CNA_Handle, const CNA_SpriteScaledCommand*, uint64_t));
CHECK_FN(cna_sprite_batch_end, CNA_Result, (CNA_Handle));
CHECK_FN(cna_sprite_batch_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_sound_effect_create_pcm16, CNA_Result, (CNA_Handle, const CNA_SoundEffectCreateInfo*, const uint8_t*, uint64_t, CNA_Handle*));
CHECK_FN(cna_sound_effect_create_pcm16_range_ext, CNA_Result, (CNA_Handle, const CNA_SoundEffectCreateInfo*, const uint8_t*, uint64_t, int32_t, int32_t, int32_t, int32_t, CNA_Handle*));
CHECK_FN(cna_sound_effect_create_from_encoded_ext, CNA_Result, (CNA_Handle, const uint8_t*, uint64_t, CNA_Handle*));
CHECK_FN(cna_sound_effect_get_duration_ticks, CNA_Result, (CNA_Handle, int64_t*));
CHECK_FN(cna_sound_effect_get_is_disposed, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_sound_effect_get_name_size, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_sound_effect_copy_name, CNA_Result, (CNA_Handle, char*, uint64_t, uint64_t*));
CHECK_FN(cna_sound_effect_set_name, CNA_Result, (CNA_Handle, CNA_StringView));
CHECK_FN(cna_sound_effect_create_instance, CNA_Result, (CNA_Handle, CNA_Handle*));
CHECK_FN(cna_sound_effect_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_sound_effect_play, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_sound_effect_play_with_settings, CNA_Result, (CNA_Handle, float, float, float, CNA_Bool*));
CHECK_FN(cna_sound_effect_get_sample_duration_ticks, CNA_Result, (int32_t, int32_t, CNA_AudioChannels, int64_t*));
CHECK_FN(cna_sound_effect_get_sample_size_in_bytes, CNA_Result, (int64_t, int32_t, CNA_AudioChannels, int32_t*));
CHECK_FN(cna_sound_effect_get_master_volume, CNA_Result, (CNA_Handle, float*));
CHECK_FN(cna_sound_effect_set_master_volume, CNA_Result, (CNA_Handle, float));
CHECK_FN(cna_sound_effect_get_distance_scale, CNA_Result, (CNA_Handle, float*));
CHECK_FN(cna_sound_effect_set_distance_scale, CNA_Result, (CNA_Handle, float));
CHECK_FN(cna_sound_effect_get_doppler_scale, CNA_Result, (CNA_Handle, float*));
CHECK_FN(cna_sound_effect_set_doppler_scale, CNA_Result, (CNA_Handle, float));
CHECK_FN(cna_sound_effect_get_speed_of_sound, CNA_Result, (CNA_Handle, float*));
CHECK_FN(cna_sound_effect_set_speed_of_sound, CNA_Result, (CNA_Handle, float));
CHECK_FN(cna_sound_effect_instance_play, CNA_Result, (CNA_Handle));
CHECK_FN(cna_sound_effect_instance_pause, CNA_Result, (CNA_Handle));
CHECK_FN(cna_sound_effect_instance_resume, CNA_Result, (CNA_Handle));
CHECK_FN(cna_sound_effect_instance_stop, CNA_Result, (CNA_Handle, CNA_Bool));
CHECK_FN(cna_sound_effect_instance_get_info, CNA_Result, (CNA_Handle, CNA_SoundEffectInstanceInfo*));
CHECK_FN(cna_sound_effect_instance_set_volume, CNA_Result, (CNA_Handle, float));
CHECK_FN(cna_sound_effect_instance_set_pitch, CNA_Result, (CNA_Handle, float));
CHECK_FN(cna_sound_effect_instance_set_pan, CNA_Result, (CNA_Handle, float));
CHECK_FN(cna_sound_effect_instance_set_is_looped, CNA_Result, (CNA_Handle, CNA_Bool));
CHECK_FN(cna_sound_effect_instance_get_is_disposed, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_sound_effect_instance_apply_3d, CNA_Result, (CNA_Handle, const CNA_AudioListener*, const CNA_AudioEmitter*));
CHECK_FN(cna_sound_effect_instance_apply_3d_multi_ext, CNA_Result, (CNA_Handle, const CNA_AudioListener*, uint64_t, const CNA_AudioEmitter*));
CHECK_FN(cna_sound_effect_instance_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_dynamic_sound_effect_instance_create, CNA_Result, (CNA_Handle, int32_t, CNA_AudioChannels, CNA_Handle*));
CHECK_FN(cna_dynamic_sound_effect_instance_get_pending_buffer_count, CNA_Result, (CNA_Handle, int32_t*));
CHECK_FN(cna_dynamic_sound_effect_instance_submit_buffer, CNA_Result, (CNA_Handle, const uint8_t*, uint64_t, int32_t, int32_t));
CHECK_FN(cna_dynamic_sound_effect_instance_queue_initial_buffers_ext, CNA_Result, (CNA_Handle));
CHECK_FN(cna_dynamic_sound_effect_instance_get_sample_duration_ticks, CNA_Result, (CNA_Handle, int32_t, int64_t*));
CHECK_FN(cna_dynamic_sound_effect_instance_get_sample_size_in_bytes, CNA_Result, (CNA_Handle, int64_t, int32_t*));
CHECK_FN(cna_dynamic_sound_effect_instance_subscribe_buffer_needed, CNA_Result, (CNA_Handle, CNA_AudioEventCallback, void*, CNA_AudioEventRegistrationHandle*));
CHECK_FN(cna_audio_unsubscribe_ext, CNA_Result, (CNA_AudioEventRegistrationHandle));
CHECK_FN(cna_microphone_get_count, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_microphone_get_default_index_ext, CNA_Result, (CNA_Handle, uint64_t*, CNA_Bool*));
CHECK_FN(cna_microphone_get_name_size_at, CNA_Result, (CNA_Handle, uint64_t, uint64_t*));
CHECK_FN(cna_microphone_copy_name_at, CNA_Result, (CNA_Handle, uint64_t, char*, uint64_t, uint64_t*));
CHECK_FN(cna_microphone_get_buffer_duration_ticks_at, CNA_Result, (CNA_Handle, uint64_t, int64_t*));
CHECK_FN(cna_microphone_set_buffer_duration_ticks_at, CNA_Result, (CNA_Handle, uint64_t, int64_t));
CHECK_FN(cna_microphone_get_is_headset_at, CNA_Result, (CNA_Handle, uint64_t, CNA_Bool*));
CHECK_FN(cna_microphone_get_sample_rate_at, CNA_Result, (CNA_Handle, uint64_t, int32_t*));
CHECK_FN(cna_microphone_get_state_at, CNA_Result, (CNA_Handle, uint64_t, CNA_MicrophoneState*));
CHECK_FN(cna_microphone_start_at, CNA_Result, (CNA_Handle, uint64_t));
CHECK_FN(cna_microphone_stop_at, CNA_Result, (CNA_Handle, uint64_t));
CHECK_FN(cna_microphone_get_data_at, CNA_Result, (CNA_Handle, uint64_t, uint8_t*, uint64_t, uint64_t*));
CHECK_FN(cna_microphone_get_sample_duration_ticks_at, CNA_Result, (CNA_Handle, uint64_t, int32_t, int64_t*));
CHECK_FN(cna_microphone_get_sample_size_in_bytes_at, CNA_Result, (CNA_Handle, uint64_t, int64_t, int32_t*));
CHECK_FN(cna_microphone_subscribe_buffer_ready_at, CNA_Result, (CNA_Handle, uint64_t, CNA_AudioEventCallback, void*, CNA_AudioEventRegistrationHandle*));
CHECK_FN(cna_microphone_check_all_buffers_ext, CNA_Result, (CNA_Handle));
CHECK_FN(cna_audio_engine_create_with_renderer, CNA_Result, (CNA_Handle, CNA_StringView, int64_t, CNA_StringView, CNA_Handle*));
CHECK_FN(cna_audio_engine_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_audio_engine_get_is_disposed, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_audio_engine_update, CNA_Result, (CNA_Handle));
CHECK_FN(cna_audio_engine_get_renderer_count, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_audio_engine_get_renderer_friendly_name_size, CNA_Result, (CNA_Handle, uint64_t, uint64_t*));
CHECK_FN(cna_audio_engine_copy_renderer_friendly_name, CNA_Result, (CNA_Handle, uint64_t, char*, uint64_t, uint64_t*));
CHECK_FN(cna_audio_engine_get_renderer_id_size, CNA_Result, (CNA_Handle, uint64_t, uint64_t*));
CHECK_FN(cna_audio_engine_copy_renderer_id, CNA_Result, (CNA_Handle, uint64_t, char*, uint64_t, uint64_t*));
CHECK_FN(cna_audio_engine_get_global_variable, CNA_Result, (CNA_Handle, CNA_StringView, float*));
CHECK_FN(cna_audio_engine_set_global_variable, CNA_Result, (CNA_Handle, CNA_StringView, float));
CHECK_FN(cna_audio_engine_get_category, CNA_Result, (CNA_Handle, CNA_StringView, CNA_Handle*));
CHECK_FN(cna_audio_engine_subscribe_disposing_ext, CNA_Result, (CNA_Handle, CNA_AudioEventCallback, void*, CNA_Handle*));
CHECK_FN(cna_audio_category_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_audio_category_get_name_size, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_audio_category_copy_name, CNA_Result, (CNA_Handle, char*, uint64_t, uint64_t*));
CHECK_FN(cna_audio_category_pause, CNA_Result, (CNA_Handle));
CHECK_FN(cna_audio_category_resume, CNA_Result, (CNA_Handle));
CHECK_FN(cna_audio_category_set_volume, CNA_Result, (CNA_Handle, float));
CHECK_FN(cna_audio_category_stop, CNA_Result, (CNA_Handle, CNA_AudioStopOptions));
CHECK_FN(cna_audio_category_equals, CNA_Result, (CNA_Handle, CNA_Handle, CNA_Bool*));
CHECK_FN(cna_audio_category_get_hash_code, CNA_Result, (CNA_Handle, int32_t*));
CHECK_FN(cna_wave_bank_create, CNA_Result, (CNA_Handle, CNA_StringView, CNA_Handle*));
CHECK_FN(cna_wave_bank_create_streaming, CNA_Result, (CNA_Handle, CNA_StringView, int32_t, int16_t, CNA_Handle*));
CHECK_FN(cna_wave_bank_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_wave_bank_get_is_disposed, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_wave_bank_get_is_prepared, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_wave_bank_get_is_in_use, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_sound_bank_create, CNA_Result, (CNA_Handle, CNA_StringView, CNA_Handle*));
CHECK_FN(cna_sound_bank_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_sound_bank_get_is_disposed, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_sound_bank_get_is_in_use, CNA_Result, (CNA_Handle, CNA_Bool*));
CHECK_FN(cna_sound_bank_get_cue, CNA_Result, (CNA_Handle, CNA_StringView, CNA_Handle*));
CHECK_FN(cna_sound_bank_play_cue, CNA_Result, (CNA_Handle, CNA_StringView));
CHECK_FN(cna_sound_bank_play_cue_3d, CNA_Result, (CNA_Handle, CNA_StringView, const CNA_AudioListener*, const CNA_AudioEmitter*));
CHECK_FN(cna_cue_destroy, CNA_Result, (CNA_Handle));
CHECK_FN(cna_cue_get_info, CNA_Result, (CNA_Handle, CNA_CueInfo*));
CHECK_FN(cna_cue_get_name_size, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_cue_copy_name, CNA_Result, (CNA_Handle, char*, uint64_t, uint64_t*));
CHECK_FN(cna_cue_apply_3d, CNA_Result, (CNA_Handle, const CNA_AudioListener*, const CNA_AudioEmitter*));
CHECK_FN(cna_cue_get_variable, CNA_Result, (CNA_Handle, CNA_StringView, float*));
CHECK_FN(cna_cue_set_variable, CNA_Result, (CNA_Handle, CNA_StringView, float));
CHECK_FN(cna_cue_play, CNA_Result, (CNA_Handle));
CHECK_FN(cna_cue_pause, CNA_Result, (CNA_Handle));
CHECK_FN(cna_cue_resume, CNA_Result, (CNA_Handle));
CHECK_FN(cna_cue_stop, CNA_Result, (CNA_Handle, CNA_AudioStopOptions));
CHECK_FN(cna_keyboard_get_state, CNA_Result, (CNA_Handle, CNA_KeyboardState*));
CHECK_FN(cna_keyboard_get_state_for_player, CNA_Result, (CNA_Handle, CNA_PlayerIndex, CNA_KeyboardState*));
CHECK_FN(cna_keyboard_state_is_key_down, CNA_Result, (const CNA_KeyboardState*, CNA_Key, CNA_Bool*));
CHECK_FN(cna_keyboard_state_is_key_up, CNA_Result, (const CNA_KeyboardState*, CNA_Key, CNA_Bool*));
CHECK_FN(cna_keyboard_state_get_pressed_key_count, CNA_Result, (const CNA_KeyboardState*, uint32_t*));
CHECK_FN(cna_keyboard_state_copy_pressed_keys, CNA_Result, (const CNA_KeyboardState*, CNA_Key*, uint64_t, uint32_t*));
CHECK_FN(cna_mouse_get_state, CNA_Result, (CNA_Handle, CNA_MouseState*));
CHECK_FN(cna_mouse_set_position, CNA_Result, (CNA_Handle, int32_t, int32_t));
CHECK_FN(cna_mouse_get_window_handle, CNA_Result, (CNA_Handle, uint64_t*));
CHECK_FN(cna_mouse_set_window_handle, CNA_Result, (CNA_Handle, uint64_t));
CHECK_FN(cna_gamepad_get_state, CNA_Result, (CNA_Handle, CNA_PlayerIndex, CNA_GamePadState*));
CHECK_FN(cna_gamepad_get_state_with_dead_zone, CNA_Result, (CNA_Handle, CNA_PlayerIndex, CNA_GamePadDeadZone, CNA_GamePadState*));
CHECK_FN(cna_gamepad_get_capabilities, CNA_Result, (CNA_Handle, CNA_PlayerIndex, CNA_GamePadCapabilities*));
CHECK_FN(cna_gamepad_set_vibration, CNA_Result, (CNA_Handle, CNA_PlayerIndex, float, float, CNA_Bool*));

typedef CNA_Result (*expected_lifecycle)(CNA_Handle, const CNA_GameTime*, void*, CNA_CallbackError*);
typedef CNA_Result (*expected_begin_draw)(CNA_Handle, const CNA_GameTime*, void*, CNA_Bool*, CNA_CallbackError*);
_Static_assert(__builtin_types_compatible_p(CNA_GameLifecycleCallback, expected_lifecycle), "lifecycle callback mismatch");
_Static_assert(__builtin_types_compatible_p(CNA_GameBeginDrawCallback, expected_begin_draw), "begin-draw callback mismatch");
typedef void (*expected_gamer_async)(void*);
_Static_assert(__builtin_types_compatible_p(CNA_GamerAsyncCallback, expected_gamer_async), "gamer async callback mismatch");
typedef void (*expected_audio_event)(void*);
_Static_assert(__builtin_types_compatible_p(CNA_AudioEventCallback, expected_audio_event), "audio event callback mismatch");

#define STRUCT(type) printf("STRUCT|" #type "|%zu|%zu\n", sizeof(type), _Alignof(type))
#define FIELD(type, field) printf("FIELD|" #type "|" #field "|%zu|%zu\n", offsetof(type, field), sizeof(((type*)0)->field))
#define CONSTANT(name) printf("CONSTANT|" #name "|%llu\n", (unsigned long long)(name))
#define SIGNATURE(name, value) printf("SIGNATURE|" #name "|" value "\n")

int main(void) {
    SIGNATURE(cna_get_abi_version, "uint32_t|");
    SIGNATURE(cna_error_get_last_info, "CNA_Result|CNA_ErrorInfo*");
    SIGNATURE(cna_error_get_last_message_size, "CNA_Result|uint64_t*");
    SIGNATURE(cna_error_copy_last_message, "CNA_Result|char*,uint64_t,uint64_t*");
    SIGNATURE(cna_game_create, "CNA_Result|const CNA_GameCreateInfo*,CNA_Handle*");
    SIGNATURE(cna_game_set_frame_hooks_ext, "CNA_Result|CNA_Handle,const CNA_GameFrameHooks*");
    SIGNATURE(cna_game_run, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_game_run_one_frame, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_game_tick, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_game_request_exit, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_game_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_game_subscribe, "CNA_Result|CNA_Handle,CNA_GameEvent,CNA_GameEventCallback,void*,CNA_GameEventRegistrationHandle*");
    SIGNATURE(cna_game_unsubscribe, "CNA_Result|CNA_GameEventRegistrationHandle");
    SIGNATURE(cna_game_get_is_active, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_guide_get_is_visible, "CNA_Result|CNA_Bool*");
    SIGNATURE(cna_gamer_services_dispatcher_get_is_initialized, "CNA_Result|CNA_Bool*");
    SIGNATURE(cna_gamer_services_dispatcher_set_window_handle, "CNA_Result|uint64_t");
    SIGNATURE(cna_gamer_services_dispatcher_initialize, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_gamer_services_dispatcher_update, "CNA_Result|");
    SIGNATURE(cna_gamer_services_dispatcher_subscribe_installing_title_update_ext, "CNA_Result|CNA_GamerAsyncCallback,void*,CNA_Handle*");
    SIGNATURE(cna_gamer_unsubscribe_ext, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_game_get_is_mouse_visible, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_game_set_is_mouse_visible, "CNA_Result|CNA_Handle,CNA_Bool");
    SIGNATURE(cna_game_get_is_fixed_time_step, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_game_set_is_fixed_time_step, "CNA_Result|CNA_Handle,CNA_Bool");
    SIGNATURE(cna_game_get_target_elapsed_time_ticks, "CNA_Result|CNA_Handle,int64_t*");
    SIGNATURE(cna_game_set_target_elapsed_time_ticks, "CNA_Result|CNA_Handle,int64_t");
    SIGNATURE(cna_game_get_inactive_sleep_time_ticks, "CNA_Result|CNA_Handle,int64_t*");
    SIGNATURE(cna_game_set_inactive_sleep_time_ticks, "CNA_Result|CNA_Handle,int64_t");
    SIGNATURE(cna_game_suppress_draw, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_game_reset_elapsed_time, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_game_set_window_title, "CNA_Result|CNA_Handle,CNA_StringView");
    SIGNATURE(cna_game_window_get_title_size, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_game_window_copy_title, "CNA_Result|CNA_Handle,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_game_window_get_allow_user_resizing, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_game_window_set_allow_user_resizing, "CNA_Result|CNA_Handle,CNA_Bool");
    SIGNATURE(cna_game_window_get_client_bounds, "CNA_Result|CNA_Handle,CNA_Rectangle*");
    SIGNATURE(cna_game_window_get_current_orientation, "CNA_Result|CNA_Handle,CNA_DisplayOrientation*");
    SIGNATURE(cna_game_window_get_native_handle_ext, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_game_window_get_screen_device_name_size, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_game_window_copy_screen_device_name, "CNA_Result|CNA_Handle,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_game_window_begin_screen_device_change, "CNA_Result|CNA_Handle,CNA_Bool");
    SIGNATURE(cna_game_window_end_screen_device_change, "CNA_Result|CNA_Handle,CNA_StringView,int32_t,int32_t");
    SIGNATURE(cna_game_window_subscribe, "CNA_Result|CNA_Handle,CNA_GameWindowEvent,CNA_GameEventCallback,void*,CNA_GameEventRegistrationHandle*");
    SIGNATURE(cna_framework_dispatcher_update, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_title_location_get_path_size, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_title_location_copy_path, "CNA_Result|CNA_Handle,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_title_location_set_path_ext, "CNA_Result|CNA_Handle,CNA_StringView");
    SIGNATURE(cna_title_container_read_ext, "CNA_Result|CNA_Handle,CNA_StringView,uint8_t*,uint64_t,uint64_t*");
    SIGNATURE(cna_game_get_content_manager_ext, "CNA_Result|CNA_Handle,CNA_Handle*");
    SIGNATURE(cna_content_manager_create, "CNA_Result|CNA_Handle,const CNA_ContentManagerCreateInfo*,CNA_Handle*");
    SIGNATURE(cna_content_manager_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_content_manager_get_root_directory_size, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_content_manager_copy_root_directory, "CNA_Result|CNA_Handle,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_content_manager_set_root_directory, "CNA_Result|CNA_Handle,CNA_StringView");
    SIGNATURE(cna_content_manager_unload, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_content_manager_load_texture2d, "CNA_Result|CNA_Handle,CNA_StringView,CNA_Handle*");
    SIGNATURE(cna_graphics_device_manager_create, "CNA_Result|CNA_Handle,CNA_GraphicsDeviceManagerHandle*");
    SIGNATURE(cna_graphics_device_manager_get_graphics_device, "CNA_Result|CNA_GraphicsDeviceManagerHandle,CNA_Handle*");
    SIGNATURE(cna_graphics_device_manager_dispose, "CNA_Result|CNA_GraphicsDeviceManagerHandle");
    SIGNATURE(cna_graphics_device_manager_destroy, "CNA_Result|CNA_GraphicsDeviceManagerHandle");
    SIGNATURE(cna_graphics_device_get_viewport, "CNA_Result|CNA_Handle,CNA_Viewport*");
    SIGNATURE(cna_graphics_device_clear_rgba, "CNA_Result|CNA_Handle,float,float,float,float");
    SIGNATURE(cna_graphics_device_get_texture, "CNA_Result|CNA_Handle,CNA_ShaderStage,uint32_t,CNA_TextureSlotInfo*");
    SIGNATURE(cna_graphics_device_set_texture, "CNA_Result|CNA_Handle,CNA_ShaderStage,uint32_t,CNA_Handle");
    SIGNATURE(cna_texture2d_create_from_encoded_memory, "CNA_Result|CNA_Handle,const uint8_t*,uint64_t,const CNA_Texture2DDecodeInfo*,CNA_Handle*");
    SIGNATURE(cna_texture2d_get_info, "CNA_Result|CNA_Handle,CNA_Texture2DInfo*");
    SIGNATURE(cna_texture2d_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_sprite_batch_create, "CNA_Result|CNA_Handle,CNA_Handle*");
    SIGNATURE(cna_sprite_batch_begin, "CNA_Result|CNA_Handle,const CNA_SpriteBatchBeginInfo*");
    SIGNATURE(cna_sprite_batch_submit_scaled_many, "CNA_Result|CNA_Handle,const CNA_SpriteScaledCommand*,uint64_t");
    SIGNATURE(cna_sprite_batch_end, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_sprite_batch_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_sound_effect_create_pcm16, "CNA_Result|CNA_Handle,const CNA_SoundEffectCreateInfo*,const uint8_t*,uint64_t,CNA_Handle*");
    SIGNATURE(cna_sound_effect_create_pcm16_range_ext, "CNA_Result|CNA_Handle,const CNA_SoundEffectCreateInfo*,const uint8_t*,uint64_t,int32_t,int32_t,int32_t,int32_t,CNA_Handle*");
    SIGNATURE(cna_sound_effect_create_from_encoded_ext, "CNA_Result|CNA_Handle,const uint8_t*,uint64_t,CNA_Handle*");
    SIGNATURE(cna_sound_effect_get_duration_ticks, "CNA_Result|CNA_Handle,int64_t*");
    SIGNATURE(cna_sound_effect_get_is_disposed, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_sound_effect_get_name_size, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_sound_effect_copy_name, "CNA_Result|CNA_Handle,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_sound_effect_set_name, "CNA_Result|CNA_Handle,CNA_StringView");
    SIGNATURE(cna_sound_effect_create_instance, "CNA_Result|CNA_Handle,CNA_Handle*");
    SIGNATURE(cna_sound_effect_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_sound_effect_play, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_sound_effect_play_with_settings, "CNA_Result|CNA_Handle,float,float,float,CNA_Bool*");
    SIGNATURE(cna_sound_effect_get_sample_duration_ticks, "CNA_Result|int32_t,int32_t,CNA_AudioChannels,int64_t*");
    SIGNATURE(cna_sound_effect_get_sample_size_in_bytes, "CNA_Result|int64_t,int32_t,CNA_AudioChannels,int32_t*");
    SIGNATURE(cna_sound_effect_get_master_volume, "CNA_Result|CNA_Handle,float*");
    SIGNATURE(cna_sound_effect_set_master_volume, "CNA_Result|CNA_Handle,float");
    SIGNATURE(cna_sound_effect_get_distance_scale, "CNA_Result|CNA_Handle,float*");
    SIGNATURE(cna_sound_effect_set_distance_scale, "CNA_Result|CNA_Handle,float");
    SIGNATURE(cna_sound_effect_get_doppler_scale, "CNA_Result|CNA_Handle,float*");
    SIGNATURE(cna_sound_effect_set_doppler_scale, "CNA_Result|CNA_Handle,float");
    SIGNATURE(cna_sound_effect_get_speed_of_sound, "CNA_Result|CNA_Handle,float*");
    SIGNATURE(cna_sound_effect_set_speed_of_sound, "CNA_Result|CNA_Handle,float");
    SIGNATURE(cna_sound_effect_instance_play, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_sound_effect_instance_pause, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_sound_effect_instance_resume, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_sound_effect_instance_stop, "CNA_Result|CNA_Handle,CNA_Bool");
    SIGNATURE(cna_sound_effect_instance_get_info, "CNA_Result|CNA_Handle,CNA_SoundEffectInstanceInfo*");
    SIGNATURE(cna_sound_effect_instance_set_volume, "CNA_Result|CNA_Handle,float");
    SIGNATURE(cna_sound_effect_instance_set_pitch, "CNA_Result|CNA_Handle,float");
    SIGNATURE(cna_sound_effect_instance_set_pan, "CNA_Result|CNA_Handle,float");
    SIGNATURE(cna_sound_effect_instance_set_is_looped, "CNA_Result|CNA_Handle,CNA_Bool");
    SIGNATURE(cna_sound_effect_instance_get_is_disposed, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_sound_effect_instance_apply_3d, "CNA_Result|CNA_Handle,const CNA_AudioListener*,const CNA_AudioEmitter*");
    SIGNATURE(cna_sound_effect_instance_apply_3d_multi_ext, "CNA_Result|CNA_Handle,const CNA_AudioListener*,uint64_t,const CNA_AudioEmitter*");
    SIGNATURE(cna_sound_effect_instance_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_dynamic_sound_effect_instance_create, "CNA_Result|CNA_Handle,int32_t,CNA_AudioChannels,CNA_Handle*");
    SIGNATURE(cna_dynamic_sound_effect_instance_get_pending_buffer_count, "CNA_Result|CNA_Handle,int32_t*");
    SIGNATURE(cna_dynamic_sound_effect_instance_submit_buffer, "CNA_Result|CNA_Handle,const uint8_t*,uint64_t,int32_t,int32_t");
    SIGNATURE(cna_dynamic_sound_effect_instance_queue_initial_buffers_ext, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_dynamic_sound_effect_instance_get_sample_duration_ticks, "CNA_Result|CNA_Handle,int32_t,int64_t*");
    SIGNATURE(cna_dynamic_sound_effect_instance_get_sample_size_in_bytes, "CNA_Result|CNA_Handle,int64_t,int32_t*");
    SIGNATURE(cna_dynamic_sound_effect_instance_subscribe_buffer_needed, "CNA_Result|CNA_Handle,CNA_AudioEventCallback,void*,CNA_AudioEventRegistrationHandle*");
    SIGNATURE(cna_audio_unsubscribe_ext, "CNA_Result|CNA_AudioEventRegistrationHandle");
    SIGNATURE(cna_microphone_get_count, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_microphone_get_default_index_ext, "CNA_Result|CNA_Handle,uint64_t*,CNA_Bool*");
    SIGNATURE(cna_microphone_get_name_size_at, "CNA_Result|CNA_Handle,uint64_t,uint64_t*");
    SIGNATURE(cna_microphone_copy_name_at, "CNA_Result|CNA_Handle,uint64_t,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_microphone_get_buffer_duration_ticks_at, "CNA_Result|CNA_Handle,uint64_t,int64_t*");
    SIGNATURE(cna_microphone_set_buffer_duration_ticks_at, "CNA_Result|CNA_Handle,uint64_t,int64_t");
    SIGNATURE(cna_microphone_get_is_headset_at, "CNA_Result|CNA_Handle,uint64_t,CNA_Bool*");
    SIGNATURE(cna_microphone_get_sample_rate_at, "CNA_Result|CNA_Handle,uint64_t,int32_t*");
    SIGNATURE(cna_microphone_get_state_at, "CNA_Result|CNA_Handle,uint64_t,CNA_MicrophoneState*");
    SIGNATURE(cna_microphone_start_at, "CNA_Result|CNA_Handle,uint64_t");
    SIGNATURE(cna_microphone_stop_at, "CNA_Result|CNA_Handle,uint64_t");
    SIGNATURE(cna_microphone_get_data_at, "CNA_Result|CNA_Handle,uint64_t,uint8_t*,uint64_t,uint64_t*");
    SIGNATURE(cna_microphone_get_sample_duration_ticks_at, "CNA_Result|CNA_Handle,uint64_t,int32_t,int64_t*");
    SIGNATURE(cna_microphone_get_sample_size_in_bytes_at, "CNA_Result|CNA_Handle,uint64_t,int64_t,int32_t*");
    SIGNATURE(cna_microphone_subscribe_buffer_ready_at, "CNA_Result|CNA_Handle,uint64_t,CNA_AudioEventCallback,void*,CNA_AudioEventRegistrationHandle*");
    SIGNATURE(cna_microphone_check_all_buffers_ext, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_audio_engine_create_with_renderer, "CNA_Result|CNA_Handle,CNA_StringView,int64_t,CNA_StringView,CNA_Handle*");
    SIGNATURE(cna_audio_engine_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_audio_engine_get_is_disposed, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_audio_engine_update, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_audio_engine_get_renderer_count, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_audio_engine_get_renderer_friendly_name_size, "CNA_Result|CNA_Handle,uint64_t,uint64_t*");
    SIGNATURE(cna_audio_engine_copy_renderer_friendly_name, "CNA_Result|CNA_Handle,uint64_t,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_audio_engine_get_renderer_id_size, "CNA_Result|CNA_Handle,uint64_t,uint64_t*");
    SIGNATURE(cna_audio_engine_copy_renderer_id, "CNA_Result|CNA_Handle,uint64_t,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_audio_engine_get_global_variable, "CNA_Result|CNA_Handle,CNA_StringView,float*");
    SIGNATURE(cna_audio_engine_set_global_variable, "CNA_Result|CNA_Handle,CNA_StringView,float");
    SIGNATURE(cna_audio_engine_get_category, "CNA_Result|CNA_Handle,CNA_StringView,CNA_Handle*");
    SIGNATURE(cna_audio_engine_subscribe_disposing_ext, "CNA_Result|CNA_Handle,CNA_AudioEventCallback,void*,CNA_Handle*");
    SIGNATURE(cna_audio_category_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_audio_category_get_name_size, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_audio_category_copy_name, "CNA_Result|CNA_Handle,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_audio_category_pause, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_audio_category_resume, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_audio_category_set_volume, "CNA_Result|CNA_Handle,float");
    SIGNATURE(cna_audio_category_stop, "CNA_Result|CNA_Handle,CNA_AudioStopOptions");
    SIGNATURE(cna_audio_category_equals, "CNA_Result|CNA_Handle,CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_audio_category_get_hash_code, "CNA_Result|CNA_Handle,int32_t*");
    SIGNATURE(cna_wave_bank_create, "CNA_Result|CNA_Handle,CNA_StringView,CNA_Handle*");
    SIGNATURE(cna_wave_bank_create_streaming, "CNA_Result|CNA_Handle,CNA_StringView,int32_t,int16_t,CNA_Handle*");
    SIGNATURE(cna_wave_bank_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_wave_bank_get_is_disposed, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_wave_bank_get_is_prepared, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_wave_bank_get_is_in_use, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_sound_bank_create, "CNA_Result|CNA_Handle,CNA_StringView,CNA_Handle*");
    SIGNATURE(cna_sound_bank_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_sound_bank_get_is_disposed, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_sound_bank_get_is_in_use, "CNA_Result|CNA_Handle,CNA_Bool*");
    SIGNATURE(cna_sound_bank_get_cue, "CNA_Result|CNA_Handle,CNA_StringView,CNA_Handle*");
    SIGNATURE(cna_sound_bank_play_cue, "CNA_Result|CNA_Handle,CNA_StringView");
    SIGNATURE(cna_sound_bank_play_cue_3d, "CNA_Result|CNA_Handle,CNA_StringView,const CNA_AudioListener*,const CNA_AudioEmitter*");
    SIGNATURE(cna_cue_destroy, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_cue_get_info, "CNA_Result|CNA_Handle,CNA_CueInfo*");
    SIGNATURE(cna_cue_get_name_size, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_cue_copy_name, "CNA_Result|CNA_Handle,char*,uint64_t,uint64_t*");
    SIGNATURE(cna_cue_apply_3d, "CNA_Result|CNA_Handle,const CNA_AudioListener*,const CNA_AudioEmitter*");
    SIGNATURE(cna_cue_get_variable, "CNA_Result|CNA_Handle,CNA_StringView,float*");
    SIGNATURE(cna_cue_set_variable, "CNA_Result|CNA_Handle,CNA_StringView,float");
    SIGNATURE(cna_cue_play, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_cue_pause, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_cue_resume, "CNA_Result|CNA_Handle");
    SIGNATURE(cna_cue_stop, "CNA_Result|CNA_Handle,CNA_AudioStopOptions");
    SIGNATURE(cna_keyboard_get_state, "CNA_Result|CNA_Handle,CNA_KeyboardState*");
    SIGNATURE(cna_keyboard_get_state_for_player, "CNA_Result|CNA_Handle,CNA_PlayerIndex,CNA_KeyboardState*");
    SIGNATURE(cna_keyboard_state_is_key_down, "CNA_Result|const CNA_KeyboardState*,CNA_Key,CNA_Bool*");
    SIGNATURE(cna_keyboard_state_is_key_up, "CNA_Result|const CNA_KeyboardState*,CNA_Key,CNA_Bool*");
    SIGNATURE(cna_keyboard_state_get_pressed_key_count, "CNA_Result|const CNA_KeyboardState*,uint32_t*");
    SIGNATURE(cna_keyboard_state_copy_pressed_keys, "CNA_Result|const CNA_KeyboardState*,CNA_Key*,uint64_t,uint32_t*");
    SIGNATURE(cna_mouse_get_state, "CNA_Result|CNA_Handle,CNA_MouseState*");
    SIGNATURE(cna_mouse_set_position, "CNA_Result|CNA_Handle,int32_t,int32_t");
    SIGNATURE(cna_mouse_get_window_handle, "CNA_Result|CNA_Handle,uint64_t*");
    SIGNATURE(cna_mouse_set_window_handle, "CNA_Result|CNA_Handle,uint64_t");
    SIGNATURE(cna_gamepad_get_state, "CNA_Result|CNA_Handle,CNA_PlayerIndex,CNA_GamePadState*");
    SIGNATURE(cna_gamepad_get_state_with_dead_zone, "CNA_Result|CNA_Handle,CNA_PlayerIndex,CNA_GamePadDeadZone,CNA_GamePadState*");
    SIGNATURE(cna_gamepad_get_capabilities, "CNA_Result|CNA_Handle,CNA_PlayerIndex,CNA_GamePadCapabilities*");
    SIGNATURE(cna_gamepad_set_vibration, "CNA_Result|CNA_Handle,CNA_PlayerIndex,float,float,CNA_Bool*");

    STRUCT(CNA_StringView); FIELD(CNA_StringView, data); FIELD(CNA_StringView, byte_length);
    STRUCT(CNA_Rectangle); FIELD(CNA_Rectangle, x); FIELD(CNA_Rectangle, y); FIELD(CNA_Rectangle, width); FIELD(CNA_Rectangle, height);
    STRUCT(CNA_ErrorInfo); FIELD(CNA_ErrorInfo, struct_size); FIELD(CNA_ErrorInfo, struct_version); FIELD(CNA_ErrorInfo, result); FIELD(CNA_ErrorInfo, category); FIELD(CNA_ErrorInfo, message_byte_length);
    STRUCT(CNA_GameTime); FIELD(CNA_GameTime, total_game_time_ticks); FIELD(CNA_GameTime, elapsed_game_time_ticks); FIELD(CNA_GameTime, is_running_slowly); FIELD(CNA_GameTime, reserved);
    STRUCT(CNA_CallbackError); FIELD(CNA_CallbackError, struct_size); FIELD(CNA_CallbackError, struct_version); FIELD(CNA_CallbackError, message);
    STRUCT(CNA_GameCallbacks); FIELD(CNA_GameCallbacks, struct_size); FIELD(CNA_GameCallbacks, struct_version); FIELD(CNA_GameCallbacks, load_content); FIELD(CNA_GameCallbacks, update); FIELD(CNA_GameCallbacks, draw); FIELD(CNA_GameCallbacks, unload_content); FIELD(CNA_GameCallbacks, exiting); FIELD(CNA_GameCallbacks, context);
    STRUCT(CNA_GameFrameHooks); FIELD(CNA_GameFrameHooks, struct_size); FIELD(CNA_GameFrameHooks, struct_version); FIELD(CNA_GameFrameHooks, initialize); FIELD(CNA_GameFrameHooks, begin_run); FIELD(CNA_GameFrameHooks, end_run); FIELD(CNA_GameFrameHooks, begin_draw); FIELD(CNA_GameFrameHooks, end_draw); FIELD(CNA_GameFrameHooks, context);
    STRUCT(CNA_GameCreateInfo); FIELD(CNA_GameCreateInfo, struct_size); FIELD(CNA_GameCreateInfo, struct_version); FIELD(CNA_GameCreateInfo, is_fixed_time_step); FIELD(CNA_GameCreateInfo, reserved); FIELD(CNA_GameCreateInfo, target_elapsed_time_ticks); FIELD(CNA_GameCreateInfo, window_title); FIELD(CNA_GameCreateInfo, callbacks);
    STRUCT(CNA_ContentManagerCreateInfo); FIELD(CNA_ContentManagerCreateInfo, struct_size); FIELD(CNA_ContentManagerCreateInfo, struct_version); FIELD(CNA_ContentManagerCreateInfo, root_directory); FIELD(CNA_ContentManagerCreateInfo, reserved);
    STRUCT(CNA_SoundEffectCreateInfo); FIELD(CNA_SoundEffectCreateInfo, struct_size); FIELD(CNA_SoundEffectCreateInfo, struct_version); FIELD(CNA_SoundEffectCreateInfo, sample_rate); FIELD(CNA_SoundEffectCreateInfo, channels); FIELD(CNA_SoundEffectCreateInfo, reserved);
    STRUCT(CNA_CueInfo); FIELD(CNA_CueInfo, struct_size); FIELD(CNA_CueInfo, struct_version); FIELD(CNA_CueInfo, is_created); FIELD(CNA_CueInfo, is_disposed); FIELD(CNA_CueInfo, is_paused); FIELD(CNA_CueInfo, is_playing); FIELD(CNA_CueInfo, is_prepared); FIELD(CNA_CueInfo, is_preparing); FIELD(CNA_CueInfo, is_stopped); FIELD(CNA_CueInfo, is_stopping);
    STRUCT(CNA_SoundEffectInstanceInfo); FIELD(CNA_SoundEffectInstanceInfo, struct_size); FIELD(CNA_SoundEffectInstanceInfo, struct_version); FIELD(CNA_SoundEffectInstanceInfo, state); FIELD(CNA_SoundEffectInstanceInfo, is_looped); FIELD(CNA_SoundEffectInstanceInfo, reserved0); FIELD(CNA_SoundEffectInstanceInfo, volume); FIELD(CNA_SoundEffectInstanceInfo, pitch); FIELD(CNA_SoundEffectInstanceInfo, pan); FIELD(CNA_SoundEffectInstanceInfo, reserved1);
    STRUCT(CNA_AudioListener); FIELD(CNA_AudioListener, struct_size); FIELD(CNA_AudioListener, struct_version); FIELD(CNA_AudioListener, forward); FIELD(CNA_AudioListener, position); FIELD(CNA_AudioListener, up); FIELD(CNA_AudioListener, velocity);
    STRUCT(CNA_AudioEmitter); FIELD(CNA_AudioEmitter, struct_size); FIELD(CNA_AudioEmitter, struct_version); FIELD(CNA_AudioEmitter, doppler_scale); FIELD(CNA_AudioEmitter, forward); FIELD(CNA_AudioEmitter, position); FIELD(CNA_AudioEmitter, up); FIELD(CNA_AudioEmitter, velocity);
    STRUCT(CNA_TextureSlotInfo); FIELD(CNA_TextureSlotInfo, struct_size); FIELD(CNA_TextureSlotInfo, struct_version); FIELD(CNA_TextureSlotInfo, bound); FIELD(CNA_TextureSlotInfo, reserved); FIELD(CNA_TextureSlotInfo, texture);
    STRUCT(CNA_Viewport); FIELD(CNA_Viewport, x); FIELD(CNA_Viewport, y); FIELD(CNA_Viewport, width); FIELD(CNA_Viewport, height); FIELD(CNA_Viewport, min_depth); FIELD(CNA_Viewport, max_depth);
    STRUCT(CNA_Texture2DInfo); FIELD(CNA_Texture2DInfo, struct_size); FIELD(CNA_Texture2DInfo, struct_version); FIELD(CNA_Texture2DInfo, width); FIELD(CNA_Texture2DInfo, height); FIELD(CNA_Texture2DInfo, level_count); FIELD(CNA_Texture2DInfo, format);
    STRUCT(CNA_SpriteBatchBeginInfo); FIELD(CNA_SpriteBatchBeginInfo, struct_size); FIELD(CNA_SpriteBatchBeginInfo, struct_version); FIELD(CNA_SpriteBatchBeginInfo, sort_mode); FIELD(CNA_SpriteBatchBeginInfo, reserved);
    STRUCT(CNA_SpriteScaledCommand); FIELD(CNA_SpriteScaledCommand, struct_size); FIELD(CNA_SpriteScaledCommand, struct_version); FIELD(CNA_SpriteScaledCommand, texture); FIELD(CNA_SpriteScaledCommand, position); FIELD(CNA_SpriteScaledCommand, source); FIELD(CNA_SpriteScaledCommand, color); FIELD(CNA_SpriteScaledCommand, rotation); FIELD(CNA_SpriteScaledCommand, origin); FIELD(CNA_SpriteScaledCommand, scale); FIELD(CNA_SpriteScaledCommand, effects); FIELD(CNA_SpriteScaledCommand, layer_depth);
    STRUCT(CNA_KeyboardState); FIELD(CNA_KeyboardState, struct_size); FIELD(CNA_KeyboardState, struct_version); FIELD(CNA_KeyboardState, pressed_key_words);
    STRUCT(CNA_MouseState); FIELD(CNA_MouseState, struct_size); FIELD(CNA_MouseState, struct_version); FIELD(CNA_MouseState, x); FIELD(CNA_MouseState, y); FIELD(CNA_MouseState, scroll_wheel); FIELD(CNA_MouseState, horizontal_scroll_wheel); FIELD(CNA_MouseState, pressed_buttons); FIELD(CNA_MouseState, reserved);
    STRUCT(CNA_Vector2); FIELD(CNA_Vector2, x); FIELD(CNA_Vector2, y);
    STRUCT(CNA_GamePadAnalogState); FIELD(CNA_GamePadAnalogState, left_thumb_stick); FIELD(CNA_GamePadAnalogState, right_thumb_stick); FIELD(CNA_GamePadAnalogState, left_trigger); FIELD(CNA_GamePadAnalogState, right_trigger);
    STRUCT(CNA_GamePadState); FIELD(CNA_GamePadState, struct_size); FIELD(CNA_GamePadState, struct_version); FIELD(CNA_GamePadState, is_connected); FIELD(CNA_GamePadState, reserved0); FIELD(CNA_GamePadState, packet_number); FIELD(CNA_GamePadState, pressed_buttons); FIELD(CNA_GamePadState, reserved1); FIELD(CNA_GamePadState, analog);
    STRUCT(CNA_GamePadCapabilities); FIELD(CNA_GamePadCapabilities, struct_size); FIELD(CNA_GamePadCapabilities, struct_version); FIELD(CNA_GamePadCapabilities, gamepad_type); FIELD(CNA_GamePadCapabilities, is_connected); FIELD(CNA_GamePadCapabilities, has_a_button); FIELD(CNA_GamePadCapabilities, has_b_button); FIELD(CNA_GamePadCapabilities, has_x_button); FIELD(CNA_GamePadCapabilities, has_y_button); FIELD(CNA_GamePadCapabilities, has_back_button); FIELD(CNA_GamePadCapabilities, has_start_button); FIELD(CNA_GamePadCapabilities, has_big_button); FIELD(CNA_GamePadCapabilities, has_dpad_up_button); FIELD(CNA_GamePadCapabilities, has_dpad_down_button); FIELD(CNA_GamePadCapabilities, has_dpad_left_button); FIELD(CNA_GamePadCapabilities, has_dpad_right_button); FIELD(CNA_GamePadCapabilities, has_left_shoulder_button); FIELD(CNA_GamePadCapabilities, has_right_shoulder_button); FIELD(CNA_GamePadCapabilities, has_left_stick_button); FIELD(CNA_GamePadCapabilities, has_right_stick_button); FIELD(CNA_GamePadCapabilities, has_left_x_thumb_stick); FIELD(CNA_GamePadCapabilities, has_left_y_thumb_stick); FIELD(CNA_GamePadCapabilities, has_right_x_thumb_stick); FIELD(CNA_GamePadCapabilities, has_right_y_thumb_stick); FIELD(CNA_GamePadCapabilities, has_left_trigger); FIELD(CNA_GamePadCapabilities, has_right_trigger); FIELD(CNA_GamePadCapabilities, has_left_vibration_motor); FIELD(CNA_GamePadCapabilities, has_right_vibration_motor); FIELD(CNA_GamePadCapabilities, has_voice_support); FIELD(CNA_GamePadCapabilities, has_light_bar_ext); FIELD(CNA_GamePadCapabilities, has_trigger_vibration_motors_ext); FIELD(CNA_GamePadCapabilities, has_misc1_ext); FIELD(CNA_GamePadCapabilities, has_paddle1_ext); FIELD(CNA_GamePadCapabilities, has_paddle2_ext); FIELD(CNA_GamePadCapabilities, has_paddle3_ext); FIELD(CNA_GamePadCapabilities, has_paddle4_ext); FIELD(CNA_GamePadCapabilities, has_touchpad_ext); FIELD(CNA_GamePadCapabilities, has_gyro_ext); FIELD(CNA_GamePadCapabilities, has_accelerometer_ext); FIELD(CNA_GamePadCapabilities, reserved);

    CONSTANT(CNA_ABI_VERSION); CONSTANT(CNA_FALSE); CONSTANT(CNA_TRUE);
    CONSTANT(CNA_RESULT_SUCCESS); CONSTANT(CNA_RESULT_NOT_SUPPORTED); CONSTANT(CNA_RESULT_THREAD); CONSTANT(CNA_RESULT_CALLBACK);
    CONSTANT(CNA_GAME_EVENT_ACTIVATED); CONSTANT(CNA_GAME_EVENT_DEACTIVATED); CONSTANT(CNA_GAME_EVENT_DISPOSED); CONSTANT(CNA_GAME_EVENT_EXITING);
    CONSTANT(CNA_GAME_WINDOW_EVENT_CLIENT_SIZE_CHANGED); CONSTANT(CNA_GAME_WINDOW_EVENT_ORIENTATION_CHANGED); CONSTANT(CNA_GAME_WINDOW_EVENT_SCREEN_DEVICE_NAME_CHANGED);
    CONSTANT(CNA_SPRITE_SORT_MODE_DEFERRED); CONSTANT(CNA_SPRITE_EFFECT_NONE); CONSTANT(CNA_SPRITE_EFFECT_FLIP_HORIZONTALLY); CONSTANT(CNA_SPRITE_EFFECT_FLIP_VERTICALLY);
    CONSTANT(CNA_MICROPHONE_STATE_STARTED); CONSTANT(CNA_MICROPHONE_STATE_STOPPED); CONSTANT(CNA_MICROPHONE_STATE_MAXIMUM);
    CONSTANT(CNA_SURFACE_FORMAT_COLOR); CONSTANT(CNA_SHADER_STAGE_PIXEL); CONSTANT(CNA_SHADER_STAGE_VERTEX); CONSTANT(CNA_TEXTURE_COLLECTION_MAX_TEXTURES);
    CONSTANT(CNA_MOUSE_BUTTON_LEFT); CONSTANT(CNA_MOUSE_BUTTON_MIDDLE); CONSTANT(CNA_MOUSE_BUTTON_RIGHT); CONSTANT(CNA_MOUSE_BUTTON_X1); CONSTANT(CNA_MOUSE_BUTTON_X2);
    CONSTANT(CNA_PLAYER_INDEX_ONE); CONSTANT(CNA_PLAYER_INDEX_TWO); CONSTANT(CNA_PLAYER_INDEX_THREE); CONSTANT(CNA_PLAYER_INDEX_FOUR);
    CONSTANT(CNA_GAMEPAD_DEAD_ZONE_NONE); CONSTANT(CNA_GAMEPAD_DEAD_ZONE_INDEPENDENT_AXES); CONSTANT(CNA_GAMEPAD_DEAD_ZONE_CIRCULAR);
    CONSTANT(CNA_GAMEPAD_BUTTON_DPAD_UP); CONSTANT(CNA_GAMEPAD_BUTTON_DPAD_DOWN); CONSTANT(CNA_GAMEPAD_BUTTON_DPAD_LEFT); CONSTANT(CNA_GAMEPAD_BUTTON_DPAD_RIGHT);
    CONSTANT(CNA_GAMEPAD_BUTTON_START); CONSTANT(CNA_GAMEPAD_BUTTON_BACK); CONSTANT(CNA_GAMEPAD_BUTTON_LEFT_STICK); CONSTANT(CNA_GAMEPAD_BUTTON_RIGHT_STICK); CONSTANT(CNA_GAMEPAD_BUTTON_LEFT_SHOULDER); CONSTANT(CNA_GAMEPAD_BUTTON_RIGHT_SHOULDER); CONSTANT(CNA_GAMEPAD_BUTTON_BIG_BUTTON);
    CONSTANT(CNA_GAMEPAD_BUTTON_A); CONSTANT(CNA_GAMEPAD_BUTTON_B); CONSTANT(CNA_GAMEPAD_BUTTON_X); CONSTANT(CNA_GAMEPAD_BUTTON_Y);
    CONSTANT(CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_LEFT); CONSTANT(CNA_GAMEPAD_BUTTON_RIGHT_TRIGGER); CONSTANT(CNA_GAMEPAD_BUTTON_LEFT_TRIGGER); CONSTANT(CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_UP); CONSTANT(CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_DOWN); CONSTANT(CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_RIGHT); CONSTANT(CNA_GAMEPAD_BUTTON_RIGHT_THUMBSTICK_LEFT); CONSTANT(CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_UP); CONSTANT(CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_DOWN); CONSTANT(CNA_GAMEPAD_BUTTON_LEFT_THUMBSTICK_RIGHT);
    CONSTANT(CNA_GAMEPAD_TYPE_UNKNOWN); CONSTANT(CNA_GAMEPAD_TYPE_GAMEPAD); CONSTANT(CNA_GAMEPAD_TYPE_WHEEL); CONSTANT(CNA_GAMEPAD_TYPE_ARCADE_STICK); CONSTANT(CNA_GAMEPAD_TYPE_FLIGHT_STICK); CONSTANT(CNA_GAMEPAD_TYPE_DANCE_PAD); CONSTANT(CNA_GAMEPAD_TYPE_GUITAR); CONSTANT(CNA_GAMEPAD_TYPE_ALTERNATE_GUITAR); CONSTANT(CNA_GAMEPAD_TYPE_DRUM_KIT); CONSTANT(CNA_GAMEPAD_TYPE_BIG_BUTTON_PAD);
    return 0;
}
