# frozen_string_literal: true

require "json"

VERTEX_ELEMENT_TYPES = %w[VertexElement VertexElementFormat VertexElementUsage].map do |name|
  "Microsoft.Xna.Framework.Graphics.#{name}"
end.freeze

OPERATORS = {"op_Equality" => "==", "op_Inequality" => "!="}.freeze

def rbs_type(type)
  return "bool" if type == "System.Boolean"
  return "Integer" if type == "System.Int32"
  return "String" if type == "System.String"
  return "Object" if type == "System.Object"
  return type.delete_prefix("Microsoft.Xna.Framework.Graphics.") if type.start_with?("Microsoft.Xna.Framework.Graphics.")

  abort "unmapped VertexElement RBS type #{type}"
end

def ruby_method(member)
  return "initialize" if member["kind"] == "constructor"

  OPERATORS.fetch(member["name"], member["name"])
end

def method_signature(member, owner)
  parameters = member.fetch("parameters", []).dup
  if OPERATORS.key?(member["name"])
    owner_index = parameters.index { |parameter| parameter["type"] == owner }
    parameters.delete_at(owner_index) if owner_index
  end
  arguments = parameters.map.with_index do |parameter, index|
    name = parameter["name"].to_s.gsub(/[^a-zA-Z0-9_]/, "_")
    name = "argument#{index}" if name.empty?
    "#{rbs_type(parameter.fetch("type"))} #{name}"
  end.join(", ")
  return_type = member["kind"] == "constructor" ? "void" : rbs_type(member.fetch("returnType"))
  "(#{arguments}) -> #{return_type}"
end

contract = JSON.parse(File.read(File.expand_path("signatures.json", __dir__)))
types = contract.fetch("types").select { |type| VERTEX_ELEMENT_TYPES.include?(type.fetch("name")) }
abort "VertexElement selection mismatch" unless types.length == VERTEX_ELEMENT_TYPES.length

lines = [
  "# This file is generated by tools/api_compat/generate_vertex_element_rbs.rb.",
  "# Parameterless construction is the established Ruby default-value projection for structs;",
  "# it does not add a second CLR constructor identity.",
  "module Microsoft", "  module Xna", "    module Framework", "      module Graphics"
]

types.each do |type|
  owner = type.fetch("name")
  short = owner.split(".").last
  members = type.fetch("members")
  lines << "        class #{short}"

  members.select { |member| member["kind"] == "field" }.each do |member|
    lines << "          #{member.fetch("name")}: #{short}"
  end

  members.select { |member| member["kind"] == "property" }.each do |member|
    name = member.fetch("name")
    value_type = rbs_type(member.fetch("type"))
    lines << "          def #{name}: () -> #{value_type}" if member["get"]
    lines << "          def #{name}=: (#{value_type} value) -> #{value_type}" if member["set"]
  end

  callable = members.select { |member| %w[constructor method].include?(member["kind"]) }
  callable.group_by { |member| ruby_method(member) }.each do |name, overloads|
    signatures = overloads.map { |member| method_signature(member, owner) }
    signatures.unshift("() -> void") if name == "initialize"
    lines << "          def #{name}: #{signatures.shift}"
    signatures.each { |signature| lines << "#{" " * (15 + name.length)}| #{signature}" }
  end
  lines << "        end" << ""
end

lines.concat(["      end", "    end", "  end", "end", ""])
destination = File.expand_path("../../sig/microsoft/xna/vertex_element.rbs", __dir__)
File.write(destination, lines.join("\n"))
puts "VERTEX_ELEMENT_RBS_TYPES=#{types.length}"
puts "VERTEX_ELEMENT_RBS_IDENTITIES=#{types.sum { |type| type.fetch("members").length }}"
