# frozen_string_literal: true

require "json"

CURVE_TYPES = %w[Curve CurveKey CurveKeyCollection CurveContinuity CurveLoopType CurveTangent].map do |name|
  "Microsoft.Xna.Framework.#{name}"
end.freeze

OPERATORS = {"op_Equality" => "==", "op_Inequality" => "!="}.freeze

def rbs_type(type)
  value = type.delete_suffix("&")
  return "nil" if value == "System.Void"
  return "bool" if value == "System.Boolean"
  return "Integer" if value == "System.Int32"
  return "Float" if value == "System.Single"
  return "Object" if value == "System.Object"
  return "Enumerator[CurveKey, nil]" if value == "System.Collections.Generic.IEnumerator`1[Microsoft.Xna.Framework.CurveKey]"
  return "Array[#{rbs_type(value.delete_suffix("[]"))}]" if value.end_with?("[]")
  return value.delete_prefix("Microsoft.Xna.Framework.") if value.start_with?("Microsoft.Xna.Framework.")

  abort "unmapped Curve RBS type #{type}"
end

def ruby_method(member)
  return ["initialize", :instance] if member["kind"] == "constructor"

  operator = OPERATORS[member["name"]]
  return [operator, :instance] if operator

  [member["name"], member["static"] ? :singleton : :instance]
end

def method_signature(member, owner)
  parameters = member.fetch("parameters", []).dup
  if OPERATORS.key?(member["name"])
    owner_index = parameters.index { |parameter| parameter["type"].delete_suffix("&") == owner }
    parameters.delete_at(owner_index) if owner_index
  end
  arguments = parameters.map.with_index do |parameter, index|
    name = parameter["name"].to_s.gsub(/[^a-zA-Z0-9_]/, "_")
    name = "argument#{index}" if name.empty?
    "#{rbs_type(parameter.fetch("type"))} #{name}"
  end.join(", ")
  return_type = member["kind"] == "constructor" ? "void" : rbs_type(member.fetch("returnType", "System.Void"))
  "(#{arguments}) -> #{return_type}"
end

contract = JSON.parse(File.read(File.expand_path("signatures.json", __dir__)))
types = contract.fetch("types").select { |type| CURVE_TYPES.include?(type.fetch("name")) }
abort "Curve selection mismatch" unless types.length == CURVE_TYPES.length

lines = [
  "# This file is generated by tools/api_compat/generate_curve_rbs.rb.",
  "# CLR ICollection/IEnumerable remain measured interfaces; Item maps to []/[]= and",
  "# IEnumerator<CurveKey> maps to a fresh fail-fast Enumerator[CurveKey, nil].",
  "module Microsoft", "  module Xna", "    module Framework"
]

types.each do |type|
  owner = type.fetch("name")
  short = owner.split(".").last
  members = type.fetch("members")
  lines << "      class #{short}"

  members.select { |member| member["kind"] == "field" }.each do |member|
    lines << "        #{member.fetch("name")}: #{rbs_type(member.fetch("type"))}"
  end

  members.select { |member| member["kind"] == "property" }.each do |member|
    name = member.fetch("name")
    prefix = member["static"] ? "self." : ""
    type_name = rbs_type(member.fetch("type"))
    property_parameters = member.fetch("parameters", []).map.with_index do |parameter, index|
      argument_name = parameter["name"].to_s.gsub(/[^a-zA-Z0-9_]/, "_")
      argument_name = "argument#{index}" if argument_name.empty?
      "#{rbs_type(parameter.fetch("type"))} #{argument_name}"
    end
    if name == "Item"
      getter_arguments = property_parameters.join(", ")
      setter_arguments = (property_parameters + ["#{type_name} value"]).join(", ")
      lines << "        def #{prefix}[]: (#{getter_arguments}) -> #{type_name}" if member["get"]
      lines << "        def #{prefix}[]=: (#{setter_arguments}) -> #{type_name}" if member["set"]
    else
      lines << "        def #{prefix}#{name}: () -> #{type_name}" if member["get"]
      lines << "        def #{prefix}#{name}=: (#{type_name} value) -> #{type_name}" if member["set"]
    end
  end

  callable = members.select { |member| %w[constructor method].include?(member["kind"]) }
  callable.group_by { |member| ruby_method(member) }.each do |(name, scope), overloads|
    prefix = scope == :singleton ? "self." : ""
    signatures = overloads.map { |member| method_signature(member, owner) }
    lines << "        def #{prefix}#{name}: #{signatures.shift}"
    signatures.each { |signature| lines << "#{" " * (14 + prefix.length + name.length)}| #{signature}" }
  end
  lines << "      end" << ""
end

lines.concat(["    end", "  end", "end", ""])
destination = File.expand_path("../../sig/microsoft/xna/curve.rbs", __dir__)
File.write(destination, lines.join("\n"))
identity_count = types.sum do |type|
  type.fetch("members").count { |member| %w[constructor method property field].include?(member["kind"]) }
end
puts "CURVE_RBS_TYPES=#{types.length}"
puts "CURVE_RBS_MEMBER_IDENTITIES=#{identity_count}"
