# frozen_string_literal: true

require "json"

PRESENTATION_TYPES = %w[Rectangle Color].map { |name| "Microsoft.Xna.Framework.#{name}" }.freeze
OPERATORS = {
  "op_Equality" => "==", "op_Inequality" => "!=", "op_Multiply" => "*"
}.freeze

def rbs_type(type)
  value = type.delete_suffix("&")
  return "nil" if value == "System.Void"
  return "bool" if value == "System.Boolean"
  return "Integer" if %w[System.Byte System.Int32 System.UInt32].include?(value)
  return "Float" if value == "System.Single"
  return "String" if value == "System.String"
  return "Object" if value == "System.Object"
  return value.delete_prefix("Microsoft.Xna.Framework.") if value.start_with?("Microsoft.Xna.Framework.")

  abort "unmapped presentation RBS type #{type}"
end

def ruby_method(member)
  return ["initialize", :instance] if member["kind"] == "constructor"

  operator = OPERATORS[member["name"]]
  return [operator, :instance] if operator

  [member["name"], member["static"] ? :singleton : :instance]
end

def method_signature(member, owner)
  parameters = member.fetch("parameters", []).dup
  if OPERATORS.key?(member["name"])
    owner_index = parameters.index { |parameter| parameter["type"].delete_suffix("&") == owner }
    parameters.delete_at(owner_index) if owner_index
  end
  outputs = parameters.select { |parameter| parameter["out"] }
  inputs = parameters.reject { |parameter| parameter["out"] }
  arguments = inputs.map.with_index do |parameter, index|
    name = parameter["name"].to_s.gsub(/[^a-zA-Z0-9_]/, "_")
    name = "argument#{index}" if name.empty?
    "#{rbs_type(parameter.fetch("type"))} #{name}"
  end.join(", ")
  return_type = member["kind"] == "constructor" ? "void" : rbs_type(member.fetch("returnType", "System.Void"))
  unless outputs.empty?
    output_types = outputs.map { |parameter| rbs_type(parameter.fetch("type")) }
    return_type = if member["returnType"] == "System.Void" && output_types.length == 1
                    output_types.first
                  elsif member["returnType"] == "System.Void"
                    "[#{output_types.join(", ")}]"
                  else
                    "[#{([return_type] + output_types).join(", ")}]"
                  end
  end
  "(#{arguments}) -> #{return_type}"
end

contract = JSON.parse(File.read(File.expand_path("signatures.json", __dir__)))
types = contract.fetch("types").select { |type| PRESENTATION_TYPES.include?(type.fetch("name")) }
abort "presentation-value selection mismatch" unless types.length == PRESENTATION_TYPES.length

lines = [
  "# This file is generated by tools/api_compat/generate_presentation_values_rbs.rb.",
  "# Repeated overload branches deliberately retain collapsed CLR ref/out identities.",
  "# Parameterless construction is the established Ruby default-value projection for structs.",
  "module Microsoft", "  module Xna", "    module Framework"
]

types.each do |type|
  owner = type.fetch("name")
  short = owner.split(".").last
  members = type.fetch("members")
  lines << "      class #{short}"

  members.select { |member| member["kind"] == "field" }.each do |member|
    lines << "        attr_accessor #{member.fetch("name")}: #{rbs_type(member.fetch("type"))}"
  end
  members.select { |member| member["kind"] == "property" }.each do |member|
    name = member.fetch("name")
    prefix = member["static"] ? "self." : ""
    type_name = rbs_type(member.fetch("type"))
    lines << "        def #{prefix}#{name}: () -> #{type_name}" if member["get"]
    lines << "        def #{prefix}#{name}=: (#{type_name} value) -> #{type_name}" if member["set"]
  end

  callable = members.select { |member| %w[constructor method].include?(member["kind"]) }
  callable.group_by { |member| ruby_method(member) }.each do |(name, scope), overloads|
    prefix = scope == :singleton ? "self." : ""
    signatures = overloads.map { |member| method_signature(member, owner) }
    signatures.unshift("() -> void") if name == "initialize"
    lines << "        def #{prefix}#{name}: #{signatures.shift}"
    signatures.each { |signature| lines << "#{" " * (14 + prefix.length + name.length)}| #{signature}" }
  end
  lines << "      end" << ""
end

lines.concat(["    end", "  end", "end", ""])
destination = File.expand_path("../../sig/microsoft/xna/presentation_values.rbs", __dir__)
File.write(destination, lines.join("\n"))
identity_count = types.sum { |type| type.fetch("members").count { |member| %w[constructor method].include?(member["kind"]) } }
puts "PRESENTATION_RBS_TYPES=#{types.length}"
puts "PRESENTATION_RBS_OVERLOAD_IDENTITIES=#{identity_count}"
