# frozen_string_literal: true

require "json"

GEOMETRY_TYPES = %w[
  Vector2 Vector3 Vector4 Quaternion Matrix Plane Ray BoundingBox BoundingSphere BoundingFrustum
  ContainmentType PlaneIntersectionType
].map { |name| "Microsoft.Xna.Framework.#{name}" }.freeze

OPERATORS = {
  "op_UnaryNegation" => "-@", "op_Equality" => "==", "op_Inequality" => "!=",
  "op_Addition" => "+", "op_Subtraction" => "-", "op_Multiply" => "*", "op_Division" => "/"
}.freeze

def rbs_type(type)
  value = type.delete_suffix("&")
  return "nil" if value == "System.Void"
  return "bool" if value == "System.Boolean"
  return "Integer" if %w[System.Int32 System.UInt32].include?(value)
  return "Float" if %w[System.Single System.Double].include?(value)
  return "String" if value == "System.String"
  return "Object" if value == "System.Object"
  return "Float?" if value == "System.Nullable`1[System.Single]"
  return "Vector3?" if value == "System.Nullable`1[Microsoft.Xna.Framework.Vector3]"
  return "Enumerable[Vector3]" if value == "System.Collections.Generic.IEnumerable`1[Microsoft.Xna.Framework.Vector3]"
  return "Array[#{rbs_type(value.delete_suffix("[]"))}]" if value.end_with?("[]")
  return value.delete_prefix("Microsoft.Xna.Framework.") if value.start_with?("Microsoft.Xna.Framework.")

  abort "unmapped RBS type #{type}"
end

def ruby_method(member, owner)
  return ["initialize", :instance] if member["kind"] == "constructor"
  operator = OPERATORS[member["name"]]
  return [operator, :instance] if operator
  [member["name"], member["static"] ? :singleton : :instance]
end

def method_signature(member, owner)
  parameters = member.fetch("parameters", []).dup
  if OPERATORS.key?(member["name"])
    owner_index = parameters.index { |parameter| parameter["type"].delete_suffix("&") == owner }
    parameters.delete_at(owner_index) if owner_index
  end
  outputs = parameters.select { |parameter| parameter["out"] }
  inputs = parameters.reject { |parameter| parameter["out"] }
  arguments = inputs.map.with_index do |parameter, index|
    name = parameter["name"].to_s.gsub(/[^a-zA-Z0-9_]/, "_")
    name = "argument#{index}" if name.empty?
    "#{rbs_type(parameter.fetch("type"))} #{name}"
  end.join(", ")
  return_type = member["kind"] == "constructor" ? "void" : rbs_type(member.fetch("returnType", "System.Void"))
  unless outputs.empty?
    output_types = outputs.map { |parameter| rbs_type(parameter.fetch("type")) }
    return_type = if member["returnType"] == "System.Void" && output_types.length == 1
                    output_types.first
                  elsif member["returnType"] == "System.Void"
                    "[#{output_types.join(", ")}]"
                  else
                    "[#{([return_type] + output_types).join(", ")}]"
                  end
  end
  "(#{arguments}) -> #{return_type}"
end

contract = JSON.parse(File.read(File.expand_path("signatures.json", __dir__)))
types = contract.fetch("types").select { |type| GEOMETRY_TYPES.include?(type.fetch("name")) }
abort "geometry selection mismatch" unless types.length == GEOMETRY_TYPES.length

lines = ["# This file is generated by tools/api_compat/generate_geometry_rbs.rb.",
         "# Every line originates in the pinned XNA contract; repeated overload branches", 
         "# deliberately retain CLR ref/out identities after Ruby projection.",
         "module Microsoft", "  module Xna", "    module Framework"]

types.each do |type|
  owner = type.fetch("name")
  short = owner.split(".").last
  lines << "      class #{short}"
  members = type.fetch("members")

  members.select { |member| member["kind"] == "field" }.each do |member|
    if member["static"]
      lines << "        #{member.fetch("name")}: #{rbs_type(member.fetch("type"))}"
    else
      lines << "        attr_accessor #{member.fetch("name")}: #{rbs_type(member.fetch("type"))}"
    end
  end

  members.select { |member| member["kind"] == "property" }.each do |member|
    name = member.fetch("name")
    kind = member["static"] ? "self." : ""
    value_type = rbs_type(member.fetch("type"))
    lines << "        def #{kind}#{name}: () -> #{value_type}" if member["get"]
    lines << "        def #{kind}#{name}=: (#{value_type} value) -> #{value_type}" if member["set"]
  end

  callable = members.select { |member| %w[constructor method].include?(member["kind"]) }
  callable.group_by { |member| ruby_method(member, owner) }.each do |(name, scope), overloads|
    prefix = scope == :singleton ? "self." : ""
    signatures = overloads.map { |member| method_signature(member, owner) }
    lines << "        def #{prefix}#{name}: #{signatures.shift}"
    signatures.each { |signature| lines << "#{" " * (14 + prefix.length + name.length)}| #{signature}" }
  end
  lines << "      end" << ""
end

lines.concat(["    end", "  end", "end", ""])
destination = File.expand_path("../../sig/microsoft/xna/geometry.rbs", __dir__)
File.write(destination, lines.join("\n"))
puts "GEOMETRY_RBS_TYPES=#{types.length}"
puts "GEOMETRY_RBS_OVERLOAD_IDENTITIES=#{types.sum { |type| type.fetch("members").count { |member| %w[constructor method].include?(member["kind"]) } }}"
