module Microsoft
  module Xna
    module Framework
      class MathHelper
        def self.ToRadians: (Float degrees) -> Float
        def self.ToDegrees: (Float radians) -> Float
        def self.Distance: (Float value1, Float value2) -> Float
        def self.Min: (Float value1, Float value2) -> Float
        def self.Max: (Float value1, Float value2) -> Float
        def self.Clamp: (Float value, Float minimum, Float maximum) -> Float
        def self.Lerp: (Float value1, Float value2, Float amount) -> Float
        def self.WrapAngle: (Float angle) -> Float
      end

      class Point
        attr_accessor X: Integer
        attr_accessor Y: Integer
        def initialize: () -> void
                      | (Integer x, Integer y) -> void
        def self.Zero: () -> Point
      end

      class GameComponentCollectionEventArgs < CNA::Runtime::EventArgs
        def initialize: (IGameComponent? gameComponent) -> void
        attr_reader GameComponent: IGameComponent?
      end

      class GameTime
        attr_reader TotalGameTime: Float
        attr_reader ElapsedGameTime: Float
        attr_reader IsRunningSlowly: bool
        def initialize: () -> void
                      | (Numeric total, Numeric elapsed) -> void
                      | (Numeric total, Numeric elapsed, bool running_slowly) -> void
      end

      class PlayerIndex
      end

      class DisplayOrientation
        Default: DisplayOrientation
        LandscapeLeft: DisplayOrientation
        LandscapeRight: DisplayOrientation
        Portrait: DisplayOrientation
        def |: (DisplayOrientation other) -> DisplayOrientation
        def &: (DisplayOrientation other) -> DisplayOrientation
      end

      class Game
        attr_reader GraphicsDevice: Graphics::GraphicsDevice?
        def initialize: () -> void
        def Run: () -> nil
        def RunOneFrame: () -> nil
        def Exit: () -> nil
        def Dispose: () -> nil
      end

      class GraphicsDeviceManager
        DefaultBackBufferWidth: Integer
        DefaultBackBufferHeight: Integer
        attr_reader GraphicsDevice: Graphics::GraphicsDevice
        def initialize: (Game game) -> void
      end
    end
  end
end
