module Microsoft
  module Xna
    module Framework
      module Graphics
        class DisplayMode
          attr_reader Width: Integer
          attr_reader Height: Integer
          attr_reader Format: SurfaceFormat
          def AspectRatio: () -> Float
          def TitleSafeArea: () -> Microsoft::Xna::Framework::Rectangle
          def ToString: () -> String
          def to_s: () -> String
        end

        class DisplayModeCollection
          def GetEnumerator: () -> Enumerator[DisplayMode, untyped]
          def []: (SurfaceFormat | Integer format) -> Enumerator[DisplayMode, untyped]
        end

        class ResourceCreatedEventArgs < CNA::Runtime::EventArgs
          attr_reader Resource: untyped
        end

        class ResourceDestroyedEventArgs < CNA::Runtime::EventArgs
          attr_reader Name: String?
          attr_reader Tag: untyped
        end

        class PresentationParameters
          def initialize: () -> void
          attr_reader BackBufferWidth: Integer
          attr_reader BackBufferHeight: Integer
          attr_reader BackBufferFormat: SurfaceFormat
          attr_reader DepthStencilFormat: DepthFormat
          attr_reader MultiSampleCount: Integer
          attr_reader DisplayOrientation: Microsoft::Xna::Framework::DisplayOrientation
          attr_reader PresentationInterval: PresentInterval
          attr_reader RenderTargetUsage: RenderTargetUsage
          attr_reader DeviceWindowHandle: Integer
          attr_reader IsFullScreen: bool
          def BackBufferWidth=: (Integer value) -> Integer
          def BackBufferHeight=: (Integer value) -> Integer
          def BackBufferFormat=: (SurfaceFormat | Integer value) -> SurfaceFormat
          def DepthStencilFormat=: (DepthFormat | Integer value) -> DepthFormat
          def MultiSampleCount=: (Integer value) -> Integer
          def DisplayOrientation=: (Microsoft::Xna::Framework::DisplayOrientation | Integer value) -> Microsoft::Xna::Framework::DisplayOrientation
          def PresentationInterval=: (PresentInterval | Integer value) -> PresentInterval
          def RenderTargetUsage=: (RenderTargetUsage | Integer value) -> RenderTargetUsage
          def DeviceWindowHandle=: (Integer value) -> Integer
          def IsFullScreen=: (bool value) -> bool
          def Bounds: () -> Microsoft::Xna::Framework::Rectangle
          def Clone: () -> PresentationParameters
        end

        # Three exception types whose whole declared surface is the standard constructor trio,
        # every one of which forwards straight to System.Exception in the pinned XNA IL.
        class DeviceLostException < ::StandardError
          def initialize: (?String? message, ?::Exception? inner) -> void
        end

        class DeviceNotResetException < ::StandardError
          def initialize: (?String? message, ?::Exception? inner) -> void
        end

        class NoSuitableGraphicsDeviceException < ::StandardError
          def initialize: (?String? message, ?::Exception? inner) -> void
        end

        class SurfaceFormat
        end

        class GraphicsDeviceStatus
          Normal: GraphicsDeviceStatus
          Lost: GraphicsDeviceStatus
          NotReset: GraphicsDeviceStatus
        end

        class GraphicsProfile
          Reach: GraphicsProfile
          HiDef: GraphicsProfile
        end

        class ClearOptions
          Target: ClearOptions
          DepthBuffer: ClearOptions
          Stencil: ClearOptions
          def |: (ClearOptions other) -> ClearOptions
          def &: (ClearOptions other) -> ClearOptions
        end

        class DepthFormat
          None: DepthFormat
          Depth16: DepthFormat
          Depth24: DepthFormat
          Depth24Stencil8: DepthFormat
        end

        class PrimitiveType
          TriangleList: PrimitiveType
          TriangleStrip: PrimitiveType
          LineList: PrimitiveType
          LineStrip: PrimitiveType
        end

        class CubeMapFace
          PositiveX: CubeMapFace
          NegativeX: CubeMapFace
          PositiveY: CubeMapFace
          NegativeY: CubeMapFace
          PositiveZ: CubeMapFace
          NegativeZ: CubeMapFace
        end

        class BufferUsage
          None: BufferUsage
          WriteOnly: BufferUsage
          def |: (BufferUsage other) -> BufferUsage
          def &: (BufferUsage other) -> BufferUsage
        end

        class FillMode
          Solid: FillMode
          WireFrame: FillMode
        end

        class IndexElementSize
          SixteenBits: IndexElementSize
          ThirtyTwoBits: IndexElementSize
        end

        class CullMode
          None: CullMode
          CullClockwiseFace: CullMode
          CullCounterClockwiseFace: CullMode
        end

        class RenderTargetUsage
          DiscardContents: RenderTargetUsage
          PreserveContents: RenderTargetUsage
          PlatformContents: RenderTargetUsage
        end

        class SetDataOptions
          None: SetDataOptions
          Discard: SetDataOptions
          NoOverwrite: SetDataOptions
          def |: (SetDataOptions other) -> SetDataOptions
          def &: (SetDataOptions other) -> SetDataOptions
        end

        class TextureAddressMode
          Wrap: TextureAddressMode
          Clamp: TextureAddressMode
          Mirror: TextureAddressMode
        end

        class Blend
          One: Blend
          Zero: Blend
          SourceColor: Blend
          InverseSourceColor: Blend
          SourceAlpha: Blend
          InverseSourceAlpha: Blend
          DestinationColor: Blend
          InverseDestinationColor: Blend
          DestinationAlpha: Blend
          InverseDestinationAlpha: Blend
          BlendFactor: Blend
          InverseBlendFactor: Blend
          SourceAlphaSaturation: Blend
        end

        class BlendFunction
          Add: BlendFunction
          Subtract: BlendFunction
          ReverseSubtract: BlendFunction
          Min: BlendFunction
          Max: BlendFunction
        end

        class ColorWriteChannels
          None: ColorWriteChannels
          Red: ColorWriteChannels
          Green: ColorWriteChannels
          Blue: ColorWriteChannels
          Alpha: ColorWriteChannels
          All: ColorWriteChannels
          def |: (ColorWriteChannels other) -> ColorWriteChannels
          def &: (ColorWriteChannels other) -> ColorWriteChannels
        end

        class CompareFunction
          Always: CompareFunction
          Never: CompareFunction
          Less: CompareFunction
          LessEqual: CompareFunction
          Equal: CompareFunction
          GreaterEqual: CompareFunction
          Greater: CompareFunction
          NotEqual: CompareFunction
        end

        class EffectParameterClass
          Scalar: EffectParameterClass
          Vector: EffectParameterClass
          Matrix: EffectParameterClass
          Object: EffectParameterClass
          Struct: EffectParameterClass
        end

        class EffectParameterType
          Void: EffectParameterType
          Bool: EffectParameterType
          Int32: EffectParameterType
          Single: EffectParameterType
          String: EffectParameterType
          Texture: EffectParameterType
          Texture1D: EffectParameterType
          Texture2D: EffectParameterType
          Texture3D: EffectParameterType
          TextureCube: EffectParameterType
        end

        class PresentInterval
          Default: PresentInterval
          One: PresentInterval
          Two: PresentInterval
          Immediate: PresentInterval
        end

        class StencilOperation
          Keep: StencilOperation
          Zero: StencilOperation
          Replace: StencilOperation
          Increment: StencilOperation
          Decrement: StencilOperation
          IncrementSaturation: StencilOperation
          DecrementSaturation: StencilOperation
          Invert: StencilOperation
        end

        class TextureFilter
          Linear: TextureFilter
          Point: TextureFilter
          Anisotropic: TextureFilter
          LinearMipPoint: TextureFilter
          PointMipLinear: TextureFilter
          MinLinearMagPointMipLinear: TextureFilter
          MinLinearMagPointMipPoint: TextureFilter
          MinPointMagLinearMipLinear: TextureFilter
          MinPointMagLinearMipPoint: TextureFilter
        end

        class Viewport
          attr_accessor X: Integer
          attr_accessor Y: Integer
          attr_accessor Width: Integer
          attr_accessor Height: Integer
          attr_accessor MinDepth: Float
          attr_accessor MaxDepth: Float
          attr_accessor Bounds: Rectangle
          attr_reader AspectRatio: Float
          attr_reader TitleSafeArea: Rectangle
          def initialize: (Rectangle bounds) -> void
                        | (Integer x, Integer y, Integer width, Integer height) -> void
          def Project: (Vector3 source, Matrix projection, Matrix view, Matrix world) -> Vector3
          def Unproject: (Vector3 source, Matrix projection, Matrix view, Matrix world) -> Vector3
        end

        class GraphicsDevice
          attr_reader IsDisposed: bool
          attr_reader Viewport: Viewport
          def Clear: (Color color) -> nil
          def SamplerStates: () -> SamplerStateCollection
          def VertexSamplerStates: () -> SamplerStateCollection
        end

        class SamplerStateCollection
          def []: (Integer index) -> SamplerState
          def []=: (Integer index, SamplerState value) -> SamplerState
        end

        module IVertexType
          def VertexDeclaration: () -> VertexDeclaration
        end

        class VertexDeclaration < GraphicsResource
          def initialize: (*untyped arguments) -> void
          attr_reader VertexStride: Integer
          def GetVertexElements: () -> Array[VertexElement]
        end

        class VertexPositionColor
          include IVertexType
          def initialize: (?Vector3 position, ?Color color) -> void
          attr_accessor Position: Vector3
          attr_accessor Color: Color
          def GetHashCode: () -> Integer
          def ToString: () -> String
          def to_s: () -> String
        end

        class VertexPositionTexture
          include IVertexType
          def initialize: (?Vector3 position, ?Vector2 texture_coordinate) -> void
          attr_accessor Position: Vector3
          attr_accessor TextureCoordinate: Vector2
          def GetHashCode: () -> Integer
          def ToString: () -> String
          def to_s: () -> String
        end

        class VertexPositionColorTexture
          include IVertexType
          def initialize: (?Vector3 position, ?Color color, ?Vector2 texture_coordinate) -> void
          attr_accessor Position: Vector3
          attr_accessor Color: Color
          attr_accessor TextureCoordinate: Vector2
          def GetHashCode: () -> Integer
          def ToString: () -> String
          def to_s: () -> String
        end

        class VertexPositionNormalTexture
          include IVertexType
          def initialize: (?Vector3 position, ?Vector3 normal, ?Vector2 texture_coordinate) -> void
          attr_accessor Position: Vector3
          attr_accessor Normal: Vector3
          attr_accessor TextureCoordinate: Vector2
          def GetHashCode: () -> Integer
          def ToString: () -> String
          def to_s: () -> String
        end

        class GraphicsResource
          attr_reader IsDisposed: bool
          attr_accessor Tag: untyped
          attr_accessor Name: String?
          attr_reader GraphicsDevice: GraphicsDevice
          def Dispose: () -> nil
        end

        class Texture < GraphicsResource
          attr_reader LevelCount: Integer
          attr_reader Format: SurfaceFormat
        end

        class Texture2D < Texture
          attr_reader Width: Integer
          attr_reader Height: Integer
          attr_reader Bounds: Rectangle
          def self.FromStream: (GraphicsDevice graphics_device, untyped stream, *untyped arguments) -> Texture2D
        end

        class BlendState < GraphicsResource
          def initialize: () -> void
          attr_accessor ColorSourceBlend: Blend
          attr_accessor ColorDestinationBlend: Blend
          attr_accessor ColorBlendFunction: BlendFunction
          attr_accessor AlphaSourceBlend: Blend
          attr_accessor AlphaDestinationBlend: Blend
          attr_accessor AlphaBlendFunction: BlendFunction
          attr_accessor ColorWriteChannels: ColorWriteChannels
          attr_accessor ColorWriteChannels1: ColorWriteChannels
          attr_accessor ColorWriteChannels2: ColorWriteChannels
          attr_accessor ColorWriteChannels3: ColorWriteChannels
          attr_accessor BlendFactor: Color
          attr_accessor MultiSampleMask: Integer
        end

        class DepthStencilState < GraphicsResource
          def initialize: () -> void
          attr_accessor DepthBufferEnable: bool
          attr_accessor DepthBufferWriteEnable: bool
          attr_accessor DepthBufferFunction: CompareFunction
          attr_accessor StencilEnable: bool
          attr_accessor StencilFunction: CompareFunction
          attr_accessor StencilPass: StencilOperation
          attr_accessor StencilFail: StencilOperation
          attr_accessor StencilDepthBufferFail: StencilOperation
          attr_accessor TwoSidedStencilMode: bool
          attr_accessor CounterClockwiseStencilFunction: CompareFunction
          attr_accessor CounterClockwiseStencilPass: StencilOperation
          attr_accessor CounterClockwiseStencilFail: StencilOperation
          attr_accessor CounterClockwiseStencilDepthBufferFail: StencilOperation
          attr_accessor StencilMask: Integer
          attr_accessor StencilWriteMask: Integer
          attr_accessor ReferenceStencil: Integer
        end

        class RasterizerState < GraphicsResource
          def initialize: () -> void
          attr_accessor CullMode: CullMode
          attr_accessor FillMode: FillMode
          attr_accessor ScissorTestEnable: bool
          attr_accessor MultiSampleAntiAlias: bool
          attr_accessor DepthBias: Float
          attr_accessor SlopeScaleDepthBias: Float
        end

        class SamplerState < GraphicsResource
          def initialize: () -> void
          attr_accessor Filter: TextureFilter
          attr_accessor AddressU: TextureAddressMode
          attr_accessor AddressV: TextureAddressMode
          attr_accessor AddressW: TextureAddressMode
          attr_accessor MaxAnisotropy: Integer
          attr_accessor MaxMipLevel: Integer
          attr_accessor MipMapLevelOfDetailBias: Float
        end

        class SpriteBatch < GraphicsResource
          def initialize: (GraphicsDevice graphics_device) -> void
          def Begin: () -> nil
          def Draw: (*untyped arguments) -> nil
          def End: () -> nil
        end
      end
    end
  end
end
